### PR TITLE
retired google maps API version

### PR DESCRIPTION
**Pull request by bodaonline**
Edited this <script src="//maps.google.com/maps/api/js?v=.... bit since the 3.18 google API retired.

### CODE REVIEW

**Comment by apneadiving** [comment]
Thanks :)

**Comment by bodaonline** [comment]
Welcome. My first pull request :)

**Comment by lachances** [comment]
Maps stopped working in my apps because of Google's API change.
Just saw this pull request was merged in, but gem version was not updated. Shouldn't it be? Otherwise how can we update the gem in our apps?
Thanks

**Comment by apneadiving** [comment]
You have to update the google scripts.
Doc has been updated

**Pull request merged**
