### PR TITLE
Fix CDN URLs for infobox, etc.

### PR DESCRIPTION
**Pull request by kodecharlie**
Benjamin, per e-mail discussion, I have modified view_helper.rb in my forked repo
to reference new CDN URLs for infobox and other javascript resources that Google
move earlier last month.  

Once you merge these changes to 1.x, will "gem install" pick them up?

Thanks,
kodecharlie

### CODE REVIEW

**Comment by apneadiving** [comment]
I’ll have to deploy a new gem version, but thats fine :)

On 6 June 2016 at 10:41:46, kodecharlie (notifications@github.com) wrote:

Benjamin, per e-mail discussion, I have modified view_helper.rb in my
forked repo
to reference new CDN URLs for infobox and other javascript resources that
Google
move earlier last month.

Once you merge these changes to 1.x, will "gem install" pick them up?

Thanks,
kodecharlie
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/apneadiving/Google-Maps-for-Rails/pull/519
Commit Summary

   - Fix CDN URLs for infobox, etc.

File Changes

   - *M* lib/gmaps4rails/view_helper.rb
   <https://github.com/apneadiving/Google-Maps-for-Rails/pull/519/files#diff-0>
   (6)

Patch Links:

   - https://github.com/apneadiving/Google-Maps-for-Rails/pull/519.patch
   - https://github.com/apneadiving/Google-Maps-for-Rails/pull/519.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/apneadiving/Google-Maps-for-Rails/pull/519>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAPHH-lM_iLEh-SeY_Xip2Q6BuhjkFzOks5qI91JgaJpZM4IurQ5>
.

**Comment by naoisegolden** [comment]
@apneadiving will this be fix be implemented for the `2.x` version? The dependency is moved to "outside", but it would be even better to disable external libraries if you are not using the feature.

**Comment by apneadiving** [comment]
@naoisegolden google maps is indeed a dependency and its not included in the gem anymore so you can manage it easily. Same logic for the others which are already optional if you dont need clustering etc... So no fix will be implemented since there is nothing to fix

**Comment by naoisegolden** [comment]
@apneadiving clustering is external to google maps, and is a hard dependency in the code… not including it breaks the js. 
https://github.com/apneadiving/Google-Maps-for-Rails/blob/master/vendor/assets/javascripts/gmaps/google/primitives.coffee#L14

**Comment by apneadiving** [comment]
@naoisegolden ok indeed :) it could be conditionaly defined then, Could be misleading though. I'd say advanced users could simply defined an empty object in their namespace.

**Comment by naoisegolden** [comment]
@apneadiving creating an empty object in global scope gives you an `active_admin-f1f03f3….js:22388 Uncaught TypeError: this.primitives(...).clusterer is not a constructor` error.

I can create a conditional definition in a PR if you think it's fit.

**Comment by apneadiving** [comment]
@naisegolden, sorry I meant an empty function. Most people use clustering or are beginners so I feel like its easier to keep it as it is: at least it fails clearly if the dependency is missing

**Pull request merged**
